server:
  port: 8080
mybatis-plus:
  typeEnumsPackage: com.ouresports.grimstroke.*.enums
  mapper-locations: classpath:/mapper/*Mapper.xml
spring:
  datasource:
    dynamic:
      primary: grimstroke
      datasource:
        grimstroke:
          username: root
          password:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/grimstroke_dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
        arcwarden:
          username: root
          password:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/arc-warden_dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
  redis:
    host: localhost
    port: 6379
    password:
    database: 7
    jedis:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8
        max-wait: -1

